version: '3.8'
services:
    db:
        image: mysql:5.7
        container_name: mySql
        env_file: .env
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USERNAME}
            MYSQL_PASSWORD: ${MYSQL_PASS}
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASS}
        ports:
            - ${MYSQL_PORT}:${MYSQL_PORT}

    app:
        container_name: assetsApi
        build:
            context: .
            dockerfile: ./Dockerfile.local
        env_file: .env
        ports:
            - ${APP_PORT}:${APP_PORT}
        depends_on:
            - db
        restart: on-failure
